dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
before_install:
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - wget -N
  - http://chromedriver.storage.googleapis.com
  /2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver
  /usr/local/bin/chromedriver
  - sleep 3
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test authentication --keepdb
deploy:
  provider: heroku
  app: decide-full-guadalfeo-auth
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  run: "cd decide && python ./manage.py loaddata db.json"
  on:
    branch: develop